# Problem 1 

In [13]:
# 1 - numpy kütüphanesini import edin

# 2 - 5 elemanlı bir numpy array oluşturun

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.


import numpy as np
a=np.array([2,8,75,89,66])
print(np.sort(a))


[ 2  8 66 75 89]


# Problem 2

In [12]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.


# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.


# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.


# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.


# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.


# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.


# 8- [-1 ile 1] arasında 10 adet sayı üretin.


# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.


# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?


# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.


# 14- Üretilen dizinin elemanlarını tersten yazdırın.


# 15- Üretilen matrisin ilk satırını seçiniz.


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.


# 18- Üretilen matrisin her bir elemanının karesini alınız.


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.


x=np.array([10,15,30,45,60])
print(x)

y=np.arange(5,15)
print(y)

z=np.arange(5,100,5)
print(z)

np.zeros(10)

np.ones(10)

t=np.linspace(0,100,5)
print(t)

v=np.random.randint(10,30, size=5)
print(v)

c=np.random.uniform(-1,1, size=10)
print(c)

b=np.random.randint(10,50, size=(3,5))
print(b)

print(b.sum(axis=0))
print(b.sum(axis=1))

print(np.min(b))
print(np.max(b))
print(np.mean(b))

max_deger=b[0,0]
for i in range(b.shape[0]):
    for z in range(b.shape[1]):
        if b[i,z]>max_deger:
            max_deger=b[i,z]
print(max_deger)

d=np.random.randint(10,20, size=8)
print(d)
print(d[:3])

print(d[::-1])

d1=d.reshape(2,4)
print(d1)
print(d1[0,:])

print(d1[1,2])

print(d1[:,0])

print(d1**2)

e=np.random.randint(-50,50,size=[5,5])
print(e)
e1=e[e>0]
print(e1[e1%2==0])






[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[  0.  25.  50.  75. 100.]
[16 20 18 17 18]
[ 0.79760341 -0.07799348  0.09567749 -0.59105112 -0.46403725 -0.7939942
 -0.79995178 -0.29494013 -0.16402979  0.28544741]
[[21 27 36 34 16]
 [32 29 22 27 16]
 [11 43 48 37 40]]
[ 64  99 106  98  72]
[134 126 179]
11
48
29.266666666666666
48
[14 12 17 16 11 17 11 19]
[14 12 17]
[19 11 17 11 16 17 12 14]
[[14 12 17 16]
 [11 17 11 19]]
[14 12 17 16]
11
[14 11]
[[196 144 289 256]
 [121 289 121 361]]
[[-13 -45  30   2 -12]
 [ 49 -22 -22  48  29]
 [ 25  32 -11   2 -26]
 [ -3  21  10  44  -3]
 [ 14 -13 -38 -49 -26]]
[30  2 48 32  2 10 44 14]
